indent = 4
margin = 92
remove_extra_newlines = true
always_use_return = false
whitespace_typedefs = false
whitespace_ops_in_indices = false
format_docstrings = true
annotate_untyped_fields_with_any = false
format_comments = true
conditional_to_if = true
disallow_single_arg_nesting = true
always_for_in = true
for_in_replacement = "∈"
surround_whereop_typeparameters = false
