name = "NACE"
uuid = "2447ffcc-b25e-4e3a-a848-5402729e1942"
authors = ["Adrian Borucki <ntoxeg@llu.cc>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
